# NGAP procedure codes from 3GPP TS 38.413
NGAP_PROCEDURE_CODES = {
    0: "AMF Configuration Update",
    1: "AMF Status Indication",
    2: "Cell Traffic Trace",
    3: "Deactivate Trace",
    4: "Downlink NAS Transport",
    5: "Downlink Non UE Associated NRPPa Transport",
    6: "Downlink RAN Configuration Transfer",
    7: "Downlink RAN Status Transfer",
    8: "Downlink UE Associated NRPPa Transport",
    9: "Error Indication",
    10: "Handover Cancel",
    11: "Handover Notification",
    12: "Handover Preparation",
    13: "Handover Resource Allocation",
    14: "Initial Context Setup",
    15: "Initial UE Message",
    16: "Location Reporting Control",
    17: "Location Reporting Failure Indication",
    18: "Location Report",
    19: "NAS Non Delivery Indication",
    20: "NG Reset",
    21: "NG Setup",
    22: "Overload Start",
    23: "Overload Stop",
    24: "Paging",
    25: "Path Switch Request",
    26: "PDU Session Resource Modify",
    27: "PDU Session Resource Modify Indication",
    28: "PDU Session Resource Release",
    29: "PDU Session Resource Setup",
    30: "PDU Session Resource Notify",
    31: "Private Message",
    32: "PWS Cancel",
    33: "PWS Failure Indication",
    34: "PWS Restart Indication",
    35: "RAN Configuration Update",
    36: "Reroute NAS Request",
    37: "RRC Inactive Transition Report",
    38: "Trace Failure Indication",
    39: "Trace Start",
    40: "UE Context Modification",
    41: "UE Context Release",
    42: "UE Context Release Request",
    43: "UE Radio Capability Check",
    44: "UE Radio Capability Info Indication",
    45: "UE TNLA Binding Release",
    46: "Uplink NAS Transport",
    47: "Uplink Non UE Associated NRPPa Transport",
    48: "Uplink RAN Configuration Transfer",
    49: "Uplink RAN Status Transfer",
    50: "Uplink UE Associated NRPPa Transport",
    51: "Write Replace Warning",
    52: "Secondary RAT Data Usage Report",
    53: "Uplink RIM Information Transfer",
    54: "Downlink RIM Information Transfer",
    55: "Retrieve UE Information",
    56: "UE Information Transfer",
    57: "RAN CP Relocation Indication",
    58: "UE Context Resume",
    59: "UE Context Suspend",
    60: "UE Radio Capability ID Mapping",
    61: "Handover Success",
    62: "Uplink RAN Early Status Transfer",
    63: "Downlink RAN Early Status Transfer",
    64: "AMF CP Relocation Indication",
    65: "Connection Establishment Indication",
    66: "Broadcast Session Modification",
    67: "Broadcast Session Release",
    68: "Broadcast Session Setup",
    69: "Distribution Setup",
    70: "Distribution Release",
    71: "Multicast Session Activation",
    72: "Multicast Session Deactivation",
    73: "Multicast Session Update",
    74: "Multicast Group Paging",
    75: "Broadcast Session Release Required"
}

# Direction indicators
NGAP_DIRECTION = {
    0: "Unknown",
    1: "Uplink (gNB to Core)",
    2: "Downlink (Core to gNB)"
}